#!/bin/bash
# puts ascii art into git log
# $ cowsay | gitart ./path/to/repo
# $ git log --pretty=format:%s|
set -e

DIR=${1:-./}

git -C "${DIR}" status >/dev/null 2>&1

i=0
while read -r; do
	while [[ -f "${DIR}/.${i}" ]]; do
		i=$((i + 1))
	done
	touch "${DIR}/.${i}"
	git -C "${DIR}" add ".${i}"
	git -C "${DIR}" commit -m "${REPLY}" --allow-empty-message
done < <(tac)
