#!/bin/bash
# writes ascii art into git log
# $ cowsay git gud | gitart path/to/repo
# check results with:
# $ git log --oneline
# or
# $ git log --pretty=format:%s

set -e

DIR=${1:-./}

git -C "${DIR}" status > /dev/null

while read -r; do
	echo "g" >> "${DIR}"/.gitart
	git -C "${DIR}" add .gitart
	git -C "${DIR}" commit -m "${REPLY}" --allow-empty-message > /dev/null
done < <(tac)
