#!/bin/sh

set -e

USAGE() {
	echo "Display time difference between two date strings."
	echo
	echo "Usage: timediff [-vh] DATE DATE"
	echo
	echo "Options:"
	echo "  -v	Verbose messsages"
	echo "  -h	Display help"
	echo
	echo "Examples:"
	echo "  timediff 7:06 18:31"
	echo "  timediff 213 now"
	echo "  timediff now 2023-1-1"
	echo "  timediff now next\ thursday\ 16:20"
	echo "  timediff last\ wednesday next\ friday"
	echo "  timediff \"10 days ago 1:11\" now"
	echo "  timediff \"2 april 2005 21:37\" now"
	exit 1
}

while getopts "hv" arg; do
	case $arg in
	v)
		VERBOSE=1
		shift
		;;
	h)
		USAGE
		;;
	*)
		exit 1
		;;
	esac
done

[ $# -lt 2 ] && USAGE

START=$(date -d "$1" +%s)
END=$(date -d "$2" +%s)
DIFF=$((END - START))
DAYS=$((DIFF / (60 * 60 * 24)))
HOURS=$((DIFF / (60 * 60) - 24 * DAYS))
MINUTES=$(((DIFF / 60 - 60 * HOURS - 24 * 60 * DAYS)))

[ $VERBOSE ] && echo START="$START" END="$END" DIFF="$DIFF" >&2

[ $DAYS -ne 0 ] && OUT=${OUT}${DAYS}d" "
[ $HOURS -ne 0 ] && OUT=${OUT}${HOURS}h" "
[ $MINUTES -ne 0 ] && OUT=${OUT}${MINUTES}m

echo "${OUT}"
